// Pure game data constants extracted from app.ts.
// Keep this file free of imports — consumed by both the Angular component and tests.

export const TITLES = [
  "Unpaid Intern",
  "Junior Manager",
  "Middle Manager",
  "Senior Manager",
  "Director of Synergy",
  "VP of Vague Strategy",
  "Chief Nothing Officer (CNO)",
  "Board Member",
  "Visionary Founder",
  "Corporate Deity",
];

export const SYNERGY_THRESHOLDS = [
  0, 100, 300, 600, 1200, 2500, 5000, 8000, 12000, 20000,
];

export const LIFETIME_TITLES = [
  "Promising Hire",
  "Junior Synergist",
  "Associate VP of Emails",
  "Director of Meaningless Meetings",
  "Global Head of Bureaucracy",
  "Chief Officer of Office Politics",
  "Emperor of the Ping Pong Table",
  "Deity of Deliverables",
  "The Immutable Stakeholder",
  "Intergalactic Corporate Overlord",
];
export const LIFETIME_THRESHOLDS = [
  0, 1000, 5000, 15000, 35000, 75000, 150000, 300000, 750000, 1500000,
];

export const STORY_EVENTS: Record<
  number,
  { title: string; text: string; boss: string }
> = {
  100: {
    title: "The First Win",
    text: "You forwarded your first email chain. Welcome to the team. Time to climb.",
    boss: "Line Manager",
  },
  300: {
    title: "Performance Review",
    text: "You've survived enough useless meetings to justify an existence. Here's a new title. Keep up the aesthetic of hard work.",
    boss: "VP of Synergies",
  },
  1200: {
    title: "Welcome to Middle Management",
    text: "You don't do real work anymore. You manage the people who do. Fire them if they look at you funny. We've given you a company fleece.",
    boss: "The CEO",
  },
  5000: {
    title: "The Corner Office",
    text: "You did it. You took credit for everything. The golden parachute is secured. But there's always a bigger fish...",
    boss: "The Board",
  },
  12000: {
    title: "A Paradigm Shift",
    text: "You are no longer a person. You are a brand. You speak only in LinkedIn posts.",
    boss: "Your PR Manager",
  },
};

export interface SkillNode {
  id: string;
  name: string;
  desc: string;
  cost: number;
  icon: string;
  dependencies: string[];
  type: "passive" | "action";
  keyCode?: string;
}

export const SKILL_TREE: SkillNode[] = [
  {
    id: "coffee_boost",
    name: "Premium Beans",
    desc: "Coffee breaks last 2x as long.",
    cost: 500,
    icon: "☕",
    dependencies: [],
    type: "passive",
  },
  {
    id: "combo_retain",
    name: "Retention Plan",
    desc: "Combo meter drains 30% slower.",
    cost: 1200,
    icon: "🔥",
    dependencies: ["coffee_boost"],
    type: "passive",
  },
  {
    id: "action_gaslight",
    name: "Gaslight Team",
    desc: "New Action (G): Clear all obstacles on screen. Costs 40 Morale.",
    cost: 3000,
    icon: "💨",
    dependencies: ["combo_retain"],
    type: "action",
    keyCode: "G",
  },
  {
    id: "marketing_buzz",
    name: "Buzzwords",
    desc: "Passively generate +1 Synergy every second.",
    cost: 800,
    icon: "📈",
    dependencies: [],
    type: "passive",
  },
  {
    id: "viral_referral",
    name: "Affiliate Marketing",
    desc: "Double Synergy points gained from Daily Objectives.",
    cost: 1500,
    icon: "🔗",
    dependencies: ["marketing_buzz"],
    type: "passive",
  },
  {
    id: "viral_influencer",
    name: "LinkedIn Influencer",
    desc: "Gain +2 Synergy passively every second. Unlocks elite title.",
    cost: 4000,
    icon: "🤳",
    dependencies: ["viral_referral"],
    type: "passive",
  },
  {
    id: "action_synergize_aoe",
    name: "Reply All",
    desc: "Synergize Email (E) clears ALL emails on screen.",
    cost: 2500,
    icon: "📧",
    dependencies: ["marketing_buzz"],
    type: "passive",
    keyCode: "E",
  },
  {
    id: "skill_growth_hacking_0",
    name: "Growth Hacking",
    desc: "Increases global Synergy multiplier by 0.5%.",
    cost: 8200,
    icon: "📅",
    dependencies: ["action_synergize_aoe"],
    type: "passive",
  },
  {
    id: "skill_disruptive_innovation_1",
    name: "Disruptive Innovation",
    desc: "Increases global Synergy multiplier by 0.7%.",
    cost: 8050,
    icon: "📅",
    dependencies: ["coffee_boost"],
    type: "passive",
  },
  {
    id: "skill_blockchain_integration_2",
    name: "Blockchain Integration",
    desc: "Increases global Synergy multiplier by 0.5%.",
    cost: 7412,
    icon: "📅",
    dependencies: ["action_synergize_aoe"],
    type: "passive",
  },
  {
    id: "skill_agile_transformation_3",
    name: "Agile Transformation",
    desc: "Increases global Synergy multiplier by 0.2%.",
    cost: 7787,
    icon: "🚀",
    dependencies: ["marketing_buzz"],
    type: "passive",
  },
  {
    id: "skill_six_sigma_black_belt_4",
    name: "Six Sigma Black Belt",
    desc: "Increases global Synergy multiplier by 0.9%.",
    cost: 10476,
    icon: "💼",
    dependencies: ["skill_blockchain_integration_2"],
    type: "passive",
  },
  {
    id: "skill_bleeding_edge_insights_5",
    name: "Bleeding Edge Insights",
    desc: "Increases global Synergy multiplier by 0.7%.",
    cost: 10479,
    icon: "📋",
    dependencies: ["skill_agile_transformation_3"],
    type: "passive",
  },
  {
    id: "skill_thought_leadership_6",
    name: "Thought Leadership",
    desc: "Increases global Synergy multiplier by 0.8%.",
    cost: 10697,
    icon: "💼",
    dependencies: ["action_synergize_aoe"],
    type: "passive",
  },
  {
    id: "skill_holistic_approach_7",
    name: "Holistic Approach",
    desc: "Increases global Synergy multiplier by 0.5%.",
    cost: 11831,
    icon: "💡",
    dependencies: ["skill_six_sigma_black_belt_4"],
    type: "passive",
  },
  {
    id: "skill_paradigm_shift_8",
    name: "Paradigm Shift",
    desc: "Increases global Synergy multiplier by 0.9%.",
    cost: 9082,
    icon: "🗑️",
    dependencies: ["skill_thought_leadership_6"],
    type: "passive",
  },
  {
    id: "skill_pivot_strategy_9",
    name: "Pivot Strategy",
    desc: "Increases global Synergy multiplier by 0.3%.",
    cost: 8051,
    icon: "🚀",
    dependencies: ["skill_disruptive_innovation_1"],
    type: "passive",
  },
  {
    id: "skill_blue_ocean_strategy_10",
    name: "Blue Ocean Strategy",
    desc: "Increases global Synergy multiplier by 0.9%.",
    cost: 12238,
    icon: "📋",
    dependencies: ["skill_paradigm_shift_8"],
    type: "passive",
  },
  {
    id: "skill_core_competencies_11",
    name: "Core Competencies",
    desc: "Increases global Synergy multiplier by 0.9%.",
    cost: 12344,
    icon: "📉",
    dependencies: ["skill_blue_ocean_strategy_10"],
    type: "passive",
  },
  {
    id: "skill_wheelhouse_optimization_12",
    name: "Wheelhouse Optimization",
    desc: "Increases global Synergy multiplier by 0.2%.",
    cost: 13171,
    icon: "🤝",
    dependencies: ["skill_bleeding_edge_insights_5"],
    type: "passive",
  },
  {
    id: "skill_boil_the_ocean_13",
    name: "Boil the Ocean",
    desc: "Increases global Synergy multiplier by 0.7%.",
    cost: 10619,
    icon: "💰",
    dependencies: ["skill_pivot_strategy_9"],
    type: "passive",
  },
  {
    id: "skill_low_hanging_fruit_14",
    name: "Low Hanging Fruit",
    desc: "Increases global Synergy multiplier by 0.3%.",
    cost: 14489,
    icon: "💼",
    dependencies: ["skill_holistic_approach_7"],
    type: "passive",
  },
  {
    id: "skill_wheel_reinvention_15",
    name: "Wheel Reinvention",
    desc: "Increases global Synergy multiplier by 0.10%.",
    cost: 11983,
    icon: "🏢",
    dependencies: ["skill_holistic_approach_7"],
    type: "passive",
  },
  {
    id: "skill_deep_dive_16",
    name: "Deep Dive",
    desc: "Increases global Synergy multiplier by 0.1%.",
    cost: 15202,
    icon: "📉",
    dependencies: ["skill_pivot_strategy_9"],
    type: "passive",
  },
  {
    id: "skill_bandwidth_expansion_17",
    name: "Bandwidth Expansion",
    desc: "Increases global Synergy multiplier by 0.8%.",
    cost: 12247,
    icon: "🚀",
    dependencies: ["skill_wheel_reinvention_15"],
    type: "passive",
  },
  {
    id: "skill_circle_back_18",
    name: "Circle Back",
    desc: "Increases global Synergy multiplier by 0.4%.",
    cost: 13619,
    icon: "💼",
    dependencies: ["skill_low_hanging_fruit_14"],
    type: "passive",
  },
  {
    id: "skill_ping_protocol_19",
    name: "Ping Protocol",
    desc: "Increases global Synergy multiplier by 0.2%.",
    cost: 14919,
    icon: "💼",
    dependencies: ["skill_deep_dive_16"],
    type: "passive",
  },
  {
    id: "skill_take_offline_20",
    name: "Take Offline",
    desc: "Increases global Synergy multiplier by 0.3%.",
    cost: 16149,
    icon: "📅",
    dependencies: ["skill_low_hanging_fruit_14"],
    type: "passive",
  },
  {
    id: "skill_actionable_insights_21",
    name: "Actionable Insights",
    desc: "Increases global Synergy multiplier by 0.2%.",
    cost: 17711,
    icon: "💼",
    dependencies: ["skill_circle_back_18"],
    type: "passive",
  },
  {
    id: "skill_big_data_mining_22",
    name: "Big Data Mining",
    desc: "Increases global Synergy multiplier by 0.2%.",
    cost: 17006,
    icon: "🚀",
    dependencies: ["skill_bandwidth_expansion_17"],
    type: "passive",
  },
  {
    id: "skill_cloud_native_workflow_23",
    name: "Cloud Native Workflow",
    desc: "Increases global Synergy multiplier by 0.2%.",
    cost: 15536,
    icon: "👔",
    dependencies: ["skill_big_data_mining_22"],
    type: "passive",
  },
  {
    id: "skill_value_add_24",
    name: "Value Add",
    desc: "Increases global Synergy multiplier by 0.8%.",
    cost: 16302,
    icon: "⏱️",
    dependencies: ["skill_circle_back_18"],
    type: "passive",
  },
  {
    id: "skill_game_changer_25",
    name: "Game Changer",
    desc: "Increases global Synergy multiplier by 0.3%.",
    cost: 17707,
    icon: "⏱️",
    dependencies: ["skill_actionable_insights_21"],
    type: "passive",
  },
  {
    id: "skill_win_win_scenario_26",
    name: "Win-Win Scenario",
    desc: "Increases global Synergy multiplier by 0.6%.",
    cost: 18352,
    icon: "💡",
    dependencies: ["skill_big_data_mining_22"],
    type: "passive",
  },
  {
    id: "skill_hyperlocal_targeting_27",
    name: "Hyperlocal Targeting",
    desc: "Increases global Synergy multiplier by 0.3%.",
    cost: 22939,
    icon: "🤝",
    dependencies: ["skill_take_offline_20"],
    type: "passive",
  },
  {
    id: "skill_omnichannel_execution_28",
    name: "Omnichannel Execution",
    desc: "Increases global Synergy multiplier by 0.5%.",
    cost: 24070,
    icon: "📋",
    dependencies: ["skill_hyperlocal_targeting_27"],
    type: "passive",
  },
  {
    id: "skill_touchplot_sync_29",
    name: "Touchplot Sync",
    desc: "Increases global Synergy multiplier by 0.4%.",
    cost: 22448,
    icon: "📊",
    dependencies: ["skill_game_changer_25"],
    type: "passive",
  },
  {
    id: "skill_north_star_alignment_30",
    name: "North Star Alignment",
    desc: "Increases global Synergy multiplier by 0.6%.",
    cost: 23875,
    icon: "👔",
    dependencies: ["skill_value_add_24"],
    type: "passive",
  },
  {
    id: "skill_key_deliverables_31",
    name: "Key Deliverables",
    desc: "Increases global Synergy multiplier by 0.9%.",
    cost: 23253,
    icon: "📈",
    dependencies: ["skill_win_win_scenario_26"],
    type: "passive",
  },
  {
    id: "skill_silo_busting_32",
    name: "Silo Busting",
    desc: "Increases global Synergy multiplier by 0.4%.",
    cost: 25285,
    icon: "🚀",
    dependencies: ["skill_key_deliverables_31"],
    type: "passive",
  },
  {
    id: "skill_cross_functional_synergy_33",
    name: "Cross-functional Synergy",
    desc: "Increases global Synergy multiplier by 0.4%.",
    cost: 27274,
    icon: "🏢",
    dependencies: ["skill_game_changer_25"],
    type: "passive",
  },
  {
    id: "skill_scalable_solutions_34",
    name: "Scalable Solutions",
    desc: "Increases global Synergy multiplier by 0.2%.",
    cost: 29922,
    icon: "💡",
    dependencies: ["skill_silo_busting_32"],
    type: "passive",
  },
  {
    id: "skill_optics_management_35",
    name: "Optics Management",
    desc: "Increases global Synergy multiplier by 0.3%.",
    cost: 28733,
    icon: "📅",
    dependencies: ["skill_key_deliverables_31"],
    type: "passive",
  },
  {
    id: "skill_bandwidth_reallocation_36",
    name: "Bandwidth Reallocation",
    desc: "Increases global Synergy multiplier by 0.5%.",
    cost: 31109,
    icon: "💰",
    dependencies: ["skill_touchplot_sync_29"],
    type: "passive",
  },
  {
    id: "skill_stakeholder_alignment_37",
    name: "Stakeholder Alignment",
    desc: "Increases global Synergy multiplier by 0.10%.",
    cost: 34554,
    icon: "👔",
    dependencies: ["skill_key_deliverables_31"],
    type: "passive",
  },
  {
    id: "skill_roi_maximization_38",
    name: "ROI Maximization",
    desc: "Increases global Synergy multiplier by 0.10%.",
    cost: 32671,
    icon: "📅",
    dependencies: ["skill_key_deliverables_31"],
    type: "passive",
  },
  {
    id: "skill_kpi_crushing_39",
    name: "KPI Crushing",
    desc: "Increases global Synergy multiplier by 0.3%.",
    cost: 36864,
    icon: "📅",
    dependencies: ["skill_cross_functional_synergy_33"],
    type: "passive",
  },
  {
    id: "skill_data_driven_decisions_40",
    name: "Data-Driven Decisions",
    desc: "Increases global Synergy multiplier by 0.4%.",
    cost: 37037,
    icon: "📅",
    dependencies: ["skill_roi_maximization_38"],
    type: "passive",
  },
  {
    id: "skill_customer_centricity_41",
    name: "Customer Centricity",
    desc: "Increases global Synergy multiplier by 0.4%.",
    cost: 36893,
    icon: "📋",
    dependencies: ["skill_optics_management_35"],
    type: "passive",
  },
  {
    id: "skill_market_penetration_42",
    name: "Market Penetration",
    desc: "Increases global Synergy multiplier by 0.6%.",
    cost: 42837,
    icon: "🤝",
    dependencies: ["skill_data_driven_decisions_40"],
    type: "passive",
  },
  {
    id: "skill_first_mover_advantage_43",
    name: "First Mover Advantage",
    desc: "Increases global Synergy multiplier by 0.1%.",
    cost: 43573,
    icon: "📋",
    dependencies: ["skill_customer_centricity_41"],
    type: "passive",
  },
  {
    id: "skill_b2b_dynamics_44",
    name: "B2B Dynamics",
    desc: "Increases global Synergy multiplier by 0.9%.",
    cost: 46206,
    icon: "🤝",
    dependencies: ["skill_bandwidth_reallocation_36"],
    type: "passive",
  },
  {
    id: "skill_b2c_outreach_45",
    name: "B2C Outreach",
    desc: "Increases global Synergy multiplier by 0.8%.",
    cost: 49241,
    icon: "📋",
    dependencies: ["skill_roi_maximization_38"],
    type: "passive",
  },
  {
    id: "skill_growth_mindset_46",
    name: "Growth Mindset",
    desc: "Increases global Synergy multiplier by 0.9%.",
    cost: 49183,
    icon: "🤝",
    dependencies: ["skill_first_mover_advantage_43"],
    type: "passive",
  },
  {
    id: "skill_ideation_session_47",
    name: "Ideation Session",
    desc: "Increases global Synergy multiplier by 0.3%.",
    cost: 52837,
    icon: "📉",
    dependencies: ["skill_growth_mindset_46"],
    type: "passive",
  },
  {
    id: "skill_mindshare_capture_48",
    name: "Mindshare Capture",
    desc: "Increases global Synergy multiplier by 0.3%.",
    cost: 54408,
    icon: "🧠",
    dependencies: ["skill_customer_centricity_41"],
    type: "passive",
  },
  {
    id: "skill_strategic_alliance_49",
    name: "Strategic Alliance",
    desc: "Increases global Synergy multiplier by 0.6%.",
    cost: 58203,
    icon: "🤝",
    dependencies: ["skill_b2b_dynamics_44"],
    type: "passive",
  },
  {
    id: "skill_leverage_assets_50",
    name: "Leverage Assets",
    desc: "Increases global Synergy multiplier by 0.5%.",
    cost: 60828,
    icon: "🧠",
    dependencies: ["skill_first_mover_advantage_43"],
    type: "passive",
  },
  {
    id: "skill_monetization_engine_51",
    name: "Monetization Engine",
    desc: "Increases global Synergy multiplier by 0.6%.",
    cost: 61089,
    icon: "📋",
    dependencies: ["skill_first_mover_advantage_43"],
    type: "passive",
  },
  {
    id: "skill_future_proofing_52",
    name: "Future-Proofing",
    desc: "Increases global Synergy multiplier by 0.2%.",
    cost: 67693,
    icon: "🚀",
    dependencies: ["skill_leverage_assets_50"],
    type: "passive",
  },
  {
    id: "skill_mission_critical_53",
    name: "Mission Critical",
    desc: "Increases global Synergy multiplier by 0.2%.",
    cost: 68347,
    icon: "🏢",
    dependencies: ["skill_ideation_session_47"],
    type: "passive",
  },
  {
    id: "skill_return_on_investment_54",
    name: "Return on Investment",
    desc: "Increases global Synergy multiplier by 0.1%.",
    cost: 71059,
    icon: "📊",
    dependencies: ["skill_mindshare_capture_48"],
    type: "passive",
  },
  {
    id: "skill_skin_in_the_game_55",
    name: "Skin in the Game",
    desc: "Increases global Synergy multiplier by 0.5%.",
    cost: 76236,
    icon: "🤝",
    dependencies: ["skill_leverage_assets_50"],
    type: "passive",
  },
  {
    id: "skill_sweat_equity_56",
    name: "Sweat Equity",
    desc: "Increases global Synergy multiplier by 0.4%.",
    cost: 81587,
    icon: "🧠",
    dependencies: ["skill_mindshare_capture_48"],
    type: "passive",
  },
  {
    id: "skill_move_the_needle_57",
    name: "Move the Needle",
    desc: "Increases global Synergy multiplier by 0.2%.",
    cost: 82221,
    icon: "🧠",
    dependencies: ["skill_leverage_assets_50"],
    type: "passive",
  },
  {
    id: "skill_outside_the_box_58",
    name: "Outside the Box",
    desc: "Increases global Synergy multiplier by 0.2%.",
    cost: 86247,
    icon: "📋",
    dependencies: ["skill_future_proofing_52"],
    type: "passive",
  },
  {
    id: "skill_thought_shower_59",
    name: "Thought Shower",
    desc: "Increases global Synergy multiplier by 0.4%.",
    cost: 89474,
    icon: "📋",
    dependencies: ["skill_sweat_equity_56"],
    type: "passive",
  },
  {
    id: "skill_brain_dump_60",
    name: "Brain Dump",
    desc: "Increases global Synergy multiplier by 0.7%.",
    cost: 95512,
    icon: "📅",
    dependencies: ["skill_outside_the_box_58"],
    type: "passive",
  },
  {
    id: "skill_drill_down_61",
    name: "Drill Down",
    desc: "Increases global Synergy multiplier by 0.1%.",
    cost: 101972,
    icon: "🧠",
    dependencies: ["skill_return_on_investment_54"],
    type: "passive",
  },
  {
    id: "skill_scope_creep_management_62",
    name: "Scope Creep Management",
    desc: "Increases global Synergy multiplier by 0.8%.",
    cost: 105365,
    icon: "📋",
    dependencies: ["skill_brain_dump_60"],
    type: "passive",
  },
  {
    id: "skill_right_sizing_63",
    name: "Right-sizing",
    desc: "Increases global Synergy multiplier by 0.8%.",
    cost: 109603,
    icon: "💰",
    dependencies: ["skill_thought_shower_59"],
    type: "passive",
  },
  {
    id: "skill_downsizing_64",
    name: "Downsizing",
    desc: "Increases global Synergy multiplier by 0.6%.",
    cost: 114598,
    icon: "🤝",
    dependencies: ["skill_outside_the_box_58"],
    type: "passive",
  },
  {
    id: "skill_restructuring_65",
    name: "Restructuring",
    desc: "Increases global Synergy multiplier by 0.7%.",
    cost: 119362,
    icon: "📈",
    dependencies: ["skill_drill_down_61"],
    type: "passive",
  },
  {
    id: "skill_vertical_integration_66",
    name: "Vertical Integration",
    desc: "Increases global Synergy multiplier by 0.4%.",
    cost: 128310,
    icon: "🤝",
    dependencies: ["skill_thought_shower_59"],
    type: "passive",
  },
  {
    id: "skill_horizontal_scaling_67",
    name: "Horizontal Scaling",
    desc: "Increases global Synergy multiplier by 0.9%.",
    cost: 132955,
    icon: "🗑️",
    dependencies: ["skill_right_sizing_63"],
    type: "passive",
  },
  {
    id: "skill_360_degree_feedback_68",
    name: "360-Degree Feedback",
    desc: "Increases global Synergy multiplier by 0.5%.",
    cost: 138812,
    icon: "💼",
    dependencies: ["skill_drill_down_61"],
    type: "passive",
  },
  {
    id: "skill_open_door_policy_69",
    name: "Open Door Policy",
    desc: "Increases global Synergy multiplier by 0.7%.",
    cost: 149397,
    icon: "💡",
    dependencies: ["skill_downsizing_64"],
    type: "passive",
  },
  {
    id: "skill_culture_fit_70",
    name: "Culture Fit",
    desc: "Increases global Synergy multiplier by 0.4%.",
    cost: 151826,
    icon: "📊",
    dependencies: ["skill_scope_creep_management_62"],
    type: "passive",
  },
  {
    id: "skill_onboarding_optimization_71",
    name: "Onboarding Optimization",
    desc: "Increases global Synergy multiplier by 0.2%.",
    cost: 162517,
    icon: "⏱️",
    dependencies: ["skill_360_degree_feedback_68"],
    type: "passive",
  },
  {
    id: "skill_offboarding_streamlining_72",
    name: "Offboarding Streamlining",
    desc: "Increases global Synergy multiplier by 0.7%.",
    cost: 168687,
    icon: "🚀",
    dependencies: ["skill_culture_fit_70"],
    type: "passive",
  },
  {
    id: "skill_talent_acquisition_73",
    name: "Talent Acquisition",
    desc: "Increases global Synergy multiplier by 0.3%.",
    cost: 178456,
    icon: "💡",
    dependencies: ["skill_open_door_policy_69"],
    type: "passive",
  },
  {
    id: "skill_headcount_management_74",
    name: "Headcount Management",
    desc: "Increases global Synergy multiplier by 0.10%.",
    cost: 185443,
    icon: "💼",
    dependencies: ["skill_culture_fit_70"],
    type: "passive",
  },
  {
    id: "skill_freemium_model_75",
    name: "Freemium Model",
    desc: "Increases global Synergy multiplier by 0.7%.",
    cost: 198170,
    icon: "📉",
    dependencies: ["skill_horizontal_scaling_67"],
    type: "passive",
  },
  {
    id: "skill_a_b_testing_76",
    name: "A/B Testing",
    desc: "Increases global Synergy multiplier by 0.2%.",
    cost: 206458,
    icon: "🏢",
    dependencies: ["skill_freemium_model_75"],
    type: "passive",
  },
  {
    id: "skill_growth_loop_77",
    name: "Growth Loop",
    desc: "Increases global Synergy multiplier by 0.5%.",
    cost: 214230,
    icon: "📊",
    dependencies: ["skill_culture_fit_70"],
    type: "passive",
  },
  {
    id: "skill_viral_coefficient_78",
    name: "Viral Coefficient",
    desc: "Increases global Synergy multiplier by 0.5%.",
    cost: 226511,
    icon: "📋",
    dependencies: ["skill_onboarding_optimization_71"],
    type: "passive",
  },
  {
    id: "skill_churn_reduction_79",
    name: "Churn Reduction",
    desc: "Increases global Synergy multiplier by 0.2%.",
    cost: 235826,
    icon: "📅",
    dependencies: ["skill_viral_coefficient_78"],
    type: "passive",
  },
  {
    id: "skill_ltv_maximization_80",
    name: "LTV Maximization",
    desc: "Increases global Synergy multiplier by 0.7%.",
    cost: 251302,
    icon: "🤝",
    dependencies: ["skill_headcount_management_74"],
    type: "passive",
  },
  {
    id: "skill_cac_optimization_81",
    name: "CAC Optimization",
    desc: "Increases global Synergy multiplier by 0.5%.",
    cost: 260267,
    icon: "🧠",
    dependencies: ["skill_growth_loop_77"],
    type: "passive",
  },
  {
    id: "skill_funnel_conversion_82",
    name: "Funnel Conversion",
    desc: "Increases global Synergy multiplier by 0.1%.",
    cost: 276550,
    icon: "🏢",
    dependencies: ["skill_headcount_management_74"],
    type: "passive",
  },
  {
    id: "skill_bounce_rate_minimization_83",
    name: "Bounce Rate Minimization",
    desc: "Increases global Synergy multiplier by 0.9%.",
    cost: 287882,
    icon: "🚀",
    dependencies: ["skill_freemium_model_75"],
    type: "passive",
  },
  {
    id: "skill_net_promoter_score_84",
    name: "Net Promoter Score",
    desc: "Increases global Synergy multiplier by 0.8%.",
    cost: 301196,
    icon: "🚀",
    dependencies: ["skill_growth_loop_77"],
    type: "passive",
  },
  {
    id: "skill_customer_journey_85",
    name: "Customer Journey",
    desc: "Increases global Synergy multiplier by 0.6%.",
    cost: 319725,
    icon: "💼",
    dependencies: ["skill_growth_loop_77"],
    type: "passive",
  },
  {
    id: "skill_user_flow_86",
    name: "User Flow",
    desc: "Increases global Synergy multiplier by 0.8%.",
    cost: 335606,
    icon: "📈",
    dependencies: ["skill_customer_journey_85"],
    type: "passive",
  },
  {
    id: "skill_ui_ux_enhancement_87",
    name: "UI/UX Enhancement",
    desc: "Increases global Synergy multiplier by 0.9%.",
    cost: 349376,
    icon: "🗑️",
    dependencies: ["skill_bounce_rate_minimization_83"],
    type: "passive",
  },
  {
    id: "skill_design_thinking_88",
    name: "Design Thinking",
    desc: "Increases global Synergy multiplier by 0.8%.",
    cost: 366974,
    icon: "📈",
    dependencies: ["skill_cac_optimization_81"],
    type: "passive",
  },
  {
    id: "skill_minimum_viable_product_89",
    name: "Minimum Viable Product",
    desc: "Increases global Synergy multiplier by 0.8%.",
    cost: 386042,
    icon: "📅",
    dependencies: ["skill_cac_optimization_81"],
    type: "passive",
  },
  {
    id: "skill_product_market_fit_90",
    name: "Product Market Fit",
    desc: "Increases global Synergy multiplier by 0.6%.",
    cost: 403424,
    icon: "📋",
    dependencies: ["skill_customer_journey_85"],
    type: "passive",
  },
  {
    id: "skill_iteration_velocity_91",
    name: "Iteration Velocity",
    desc: "Increases global Synergy multiplier by 0.4%.",
    cost: 427365,
    icon: "🤝",
    dependencies: ["skill_net_promoter_score_84"],
    type: "passive",
  },
  {
    id: "skill_pivot_to_video_92",
    name: "Pivot to Video",
    desc: "Increases global Synergy multiplier by 0.1%.",
    cost: 448113,
    icon: "📉",
    dependencies: ["skill_ui_ux_enhancement_87"],
    type: "passive",
  },
  {
    id: "skill_metaverse_integration_93",
    name: "Metaverse Integration",
    desc: "Increases global Synergy multiplier by 0.2%.",
    cost: 467318,
    icon: "📋",
    dependencies: ["skill_minimum_viable_product_89"],
    type: "passive",
  },
  {
    id: "skill_web3_strategy_94",
    name: "Web3 Strategy",
    desc: "Increases global Synergy multiplier by 0.3%.",
    cost: 489933,
    icon: "⏱️",
    dependencies: ["skill_metaverse_integration_93"],
    type: "passive",
  },
  {
    id: "skill_ai_driven_development_95",
    name: "AI-Driven Development",
    desc: "Increases global Synergy multiplier by 0.6%.",
    cost: 518314,
    icon: "💼",
    dependencies: ["skill_minimum_viable_product_89"],
    type: "passive",
  },
  {
    id: "skill_machine_learning_pipeline_96",
    name: "Machine Learning Pipeline",
    desc: "Increases global Synergy multiplier by 0.7%.",
    cost: 540919,
    icon: "💰",
    dependencies: ["skill_design_thinking_88"],
    type: "passive",
  },
  {
    id: "skill_quantum_readiness_97",
    name: "Quantum Readiness",
    desc: "Increases global Synergy multiplier by 0.2%.",
    cost: 569709,
    icon: "💡",
    dependencies: ["skill_product_market_fit_90"],
    type: "passive",
  },
  {
    id: "skill_neural_network_scaling_98",
    name: "Neural Network Scaling",
    desc: "Increases global Synergy multiplier by 0.9%.",
    cost: 596449,
    icon: "🗑️",
    dependencies: ["skill_pivot_to_video_92"],
    type: "passive",
  },
  {
    id: "skill_llm_prompt_engineering_99",
    name: "LLM Prompt Engineering",
    desc: "Increases global Synergy multiplier by 0.8%.",
    cost: 629706,
    icon: "🚀",
    dependencies: ["skill_neural_network_scaling_98"],
    type: "passive",
  },
];

// =====================================
// Avatars — used in profile picker
// =====================================
  export const AVAILABLE_AVATARS = [
    { id: "drone_1", emoji: "🤖" },
    { id: "drone_2", emoji: "👽" },
    { id: "drone_3", emoji: "🥷" },
    { id: "drone_4", emoji: "🕵️" },
    { id: "drone_5", emoji: "🧛" },
    { id: "drone_6", emoji: "🧜‍♀️" },
    { id: "drone_7", emoji: "🧟" },
    { id: "drone_8", emoji: "🧞" },
  ];

// =====================================
// Game Modes
// =====================================
  export const AVAILABLE_MODES = [
    { id: "endless", name: "ENDLESS", icon: "📈", desc: "Standard Grinding" },
    {
      id: "championship",
      name: "Q3 SPRINT",
      icon: "⏱️",
      desc: "Timed 2 Minute Run",
    },
    {
      id: "takeover",
      name: "HOSTILE TAKEOVER",
      icon: "🦈",
      desc: "High Chaos Fast Speed",
    },
    { id: "quiet", name: "QUIET QUITTING", icon: "🤫", desc: "Slow & Steady" },
    {
      id: "startup",
      name: "STARTUP CHAOS",
      icon: "🚀",
      desc: "High Risk High Reward",
    },
    {
      id: "hardcore",
      name: "HARDCORE",
      icon: "🔥",
      desc: "No Margin For Error",
    },
    {
      id: "enterprise",
      name: "ENTERPRISE",
      icon: "🏢",
      desc: "Slow Bureaucracy",
    },
    {
      id: "agile",
      name: "AGILE SPRINT",
      icon: "🏃",
      desc: "Constantly Changing",
    },
    {
      id: "waterfall",
      name: "WATERFALL",
      icon: "🌊",
      desc: "Predictable but Tedious",
    },
    {
      id: "crunch",
      name: "CRUNCH TIME",
      icon: "⏳",
      desc: "Permanent Negative Morale",
    },
    {
      id: "layoff",
      name: "LAYOFF SEASON",
      icon: "✂️",
      desc: "Extremely Hostile",
    },
    {
      id: "synergy_max",
      name: "SYNERGY MAX",
      icon: "✨",
      desc: "Only Synergy Matters",
    },
    {
      id: "reorg",
      name: "REORG SURVIVOR",
      icon: "🔄",
      desc: "Confusing Objectives",
    },
    {
      id: "pivot",
      name: "THE PIVOT",
      icon: "🔙",
      desc: "Rapid Strategy Changes",
    },
    { id: "consulting", name: "CONSULTING", icon: "💼", desc: "Billing Hours" },
    {
      id: "crypto",
      name: "CRYPTO BRO",
      icon: "💸",
      desc: "Extreme Volatility",
    },
    {
      id: "ai_bubble",
      name: "AI BUBBLE",
      icon: "🤖",
      desc: "Everything is AI",
    },
    {
      id: "remote",
      name: "REMOTE WORK",
      icon: "🏠",
      desc: "Slow, More Emails",
    },
    { id: "rto", name: "RTO MANDATE", icon: "📉", desc: "Morale Drops Faster" },
    {
      id: "hybrid",
      name: "HYBRID ROLE",
      icon: "☯️",
      desc: "Unpredictable Setup",
    },
    {
      id: "freemium",
      name: "FREEMIUM API",
      icon: "🪙",
      desc: "Wait Times Required",
    },
    {
      id: "metaverse",
      name: "METAVERSE STRATEGY",
      icon: "🥽",
      desc: "Virtually Pointless",
    },
    {
      id: "outsourced",
      name: "OUTSOURCED",
      icon: "🌐",
      desc: "Somebody Else Does It",
    },
    {
      id: "offshore",
      name: "OFFSHORE TEAM",
      icon: "🏝️",
      desc: "Timezone Delays",
    },
  ];

// =====================================
// Wardrobe Skins
// =====================================
  export const AVAILABLE_SKINS = [
    {
      id: "classic",
      name: "Standard Issue Suit",
      desc: "The corporate default.",
      unlockLevel: 0,
    },
    {
      id: "fleece",
      name: "Tech Bro Fleece",
      desc: "For when you want to seem approachable.",
      unlockLevel: 2,
    },
    {
      id: "gold",
      name: "Executive Gold",
      desc: "Reserved for the C-Suite.",
      unlockLevel: 5,
    },
    {
      id: "cyber",
      name: "Neon Disruptor",
      desc: "Move fast, break things.",
      unlockLevel: 8,
    },
    {
      id: "ninja",
      name: "Scrum Ninja",
      desc: "Sprints in stealth.",
      unlockLevel: 10,
    },
    {
      id: "wizard",
      name: "Data Wizard",
      desc: "Predicts the past.",
      unlockLevel: 15,
    },
    {
      id: "pirate",
      name: "Growth Pirate",
      desc: "Aaaargh-O-I.",
      unlockLevel: 20,
    },
    {
      id: "astronaut",
      name: "Moonshot Strategist",
      desc: "Houston, we have synergy.",
      unlockLevel: 25,
    },
    {
      id: "casual",
      name: "Jeans & Blazer",
      desc: "Casual Friday veteran.",
      unlockLevel: 30,
    },
    {
      id: "goth",
      name: "Corporate Goth",
      desc: "It is not a phase, HR.",
      unlockLevel: 35,
    },
    {
      id: "robo",
      name: "Automated Executive",
      desc: "Replaced by AI.",
      unlockLevel: 40,
    },
    {
      id: "zombie",
      name: "Burnout Survivor",
      desc: "Powered by espresso and fear.",
      unlockLevel: 45,
    },
    {
      id: "ghost",
      name: "Quiet Quitter",
      desc: "Barely visible during meetings.",
      unlockLevel: 50,
    },
    {
      id: "clown",
      name: "Office Clown",
      desc: "Brings joy, misses KPIs.",
      unlockLevel: 55,
    },
    {
      id: "knight",
      name: "White Knight",
      desc: "Saves failing projects.",
      unlockLevel: 60,
    },
    {
      id: "vampire",
      name: "Time Vampire",
      desc: "Specializes in 2-hour meetings.",
      unlockLevel: 65,
    },
    {
      id: "angel",
      name: "Angel Investor",
      desc: "Sprinkles seed funding.",
      unlockLevel: 70,
    },
    {
      id: "demon",
      name: "Micromanager",
      desc: "Breathes down your neck.",
      unlockLevel: 75,
    },
    {
      id: "hacker",
      name: "10x Engineer",
      desc: "Types very fast.",
      unlockLevel: 80,
    },
    {
      id: "dinosaur",
      name: "Legacy System",
      desc: "Refuses to upgrade.",
      unlockLevel: 85,
    },
    {
      id: "superhero",
      name: "Agile Champion",
      desc: "Rescues the sprint.",
      unlockLevel: 90,
    },
    {
      id: "king",
      name: "The Founder",
      desc: "Rules with an iron fist.",
      unlockLevel: 95,
    },
    {
      id: "god",
      name: "Board Member",
      desc: "Unreachable. Unknowable.",
      unlockLevel: 100,
    },
    {
      id: "alien",
      name: "Outside Consultant",
      desc: "Doesnt understand the culture.",
      unlockLevel: 150,
    },
  ];
